if(EXISTS "D:/projects/file_search_engine/file_search_engine_tests[1]_tests.cmake")
  include("D:/projects/file_search_engine/file_search_engine_tests[1]_tests.cmake")
else()
  add_test(file_search_engine_tests_NOT_BUILT file_search_engine_tests_NOT_BUILT)
endif()
