add_test([=[TestCaseSearchServer.TestSimple]=]  D:/projects/file_search_engine/file_search_engine_tests.exe [==[--gtest_filter=TestCaseSearchServer.TestSimple]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[TestCaseSearchServer.TestSimple]=]  PROPERTIES WORKING_DIRECTORY D:/projects/file_search_engine SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[TestCaseSearchServer.TestTop5]=]  D:/projects/file_search_engine/file_search_engine_tests.exe [==[--gtest_filter=TestCaseSearchServer.TestTop5]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[TestCaseSearchServer.TestTop5]=]  PROPERTIES WORKING_DIRECTORY D:/projects/file_search_engine SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[TestCaseInvertedIndex.TestBasic]=]  D:/projects/file_search_engine/file_search_engine_tests.exe [==[--gtest_filter=TestCaseInvertedIndex.TestBasic]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[TestCaseInvertedIndex.TestBasic]=]  PROPERTIES WORKING_DIRECTORY D:/projects/file_search_engine SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[TestCaseInvertedIndex.TestBasic2]=]  D:/projects/file_search_engine/file_search_engine_tests.exe [==[--gtest_filter=TestCaseInvertedIndex.TestBasic2]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[TestCaseInvertedIndex.TestBasic2]=]  PROPERTIES WORKING_DIRECTORY D:/projects/file_search_engine SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[TestCaseInvertedIndex.TestInvertedIndexMissingWord]=]  D:/projects/file_search_engine/file_search_engine_tests.exe [==[--gtest_filter=TestCaseInvertedIndex.TestInvertedIndexMissingWord]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[TestCaseInvertedIndex.TestInvertedIndexMissingWord]=]  PROPERTIES WORKING_DIRECTORY D:/projects/file_search_engine SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  file_search_engine_tests_TESTS TestCaseSearchServer.TestSimple TestCaseSearchServer.TestTop5 TestCaseInvertedIndex.TestBasic TestCaseInvertedIndex.TestBasic2 TestCaseInvertedIndex.TestInvertedIndexMissingWord)
